spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rise?currentSchema=catalogue
    username: rise_admin
    password: roserisen
  jpa:
    hibernate:
      ddl-auto: update # validate - было  Ensure schema matches JPA entities
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    location: lasspath:db/migration
    schemas:
      - public
      - catalogue
    baseline-on-migrate: true # Use if `catalogue` is not empty
server:
  port: 8081
logging:
  level:
    sql: info
    root: info
    web: debug

